language: node_js
node_js:
  "8"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libhdf5-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
  - wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.2/src/hdf5-1.10.2.tar.gz -O /tmp/hdf5-1.10.2.tar.gz
  - tar -zxvf /tmp/hdf5-1.10.2.tar.gz
  - cd `pwd`/hdf5-1.10.2
  - ./configure --prefix=`pwd`/dist --enable-shared=yes --enable-static=no --enable-parallel=no --enable-hl --enable-build-mode=production --without-szlib
  - make -j2 2>&1 &> hdf5_screen.txt
  - make install
  - which g++
  - g++ --version
  - export HDF5_HOME=`pwd`/hdf5-1.10.2/dist
  
install:
  - export HDF5_HOME=`pwd`/hdf5-1.10.2/dist
  - export CC=gcc-7 && export CXX=g++-7
  - $CXX --version
  - npm install --longlong_type=LONGLONG53BITS --hdf5_home_linux=${HDF5_HOME}

before-scripte:
  - export LD_LIBRARY_PATH=`pwd`/hdf5-1.10.2/dist/lib:${LD_LIBRARY_PATH}
  
script:
  - `pwd`/node_modules/.bin/mocha --harmony --require should
